export const MATCH_BUTTONS = {
  TELE: "TELE",
  DEFENCE: "DEFENCE",
};

export const GAME_LOCATIONS = {
  CORAL_MARK: {
    LEFT: "CORAL_MARK_LEFT",
    MIDDLE: "CORAL_MARK_MIDDLE",
    RIGHT: "CORAL_MARK_RIGHT",
  },
  CORAL_STATION: {
    LEFT: "CORAL_STATION_LEFT",
    RIGHT: "CORAL_STATION_RIGHT",
  },
  REEF: {
    AB: "REEF_AB",
    CD: "REEF_CD",
    EF: "REEF_EF",
    GH: "REEF_GH",
    IJ: "REEF_IJ",
    KL: "REEF_KL",
  },
  REEF_LEVEL: {
    4: "4",
    3: "3",
    2: "2",
    1: "1",
  },
  NET: "NET",
  PROCESSOR: "PROCESSOR",
  HANG: {
    LEFT: "HANG_LEFT",
    MIDDLE: "HANG_MIDDLE",
    RIGHT: "HANG_RIGHT",
  },
  HANG_LEVEL: {
    PARK: "PARK",
    DEEP: "DEEP",
    SHALLOW: "SHALLOW",
    FAIL: "FAIL",
  },
  STARTING_LINE: "STARTING_LINE",
};

// hard coded for the blue-zero, scoring table perspective
// encoding is: [x, y]
export const POSITIONS = {
  [GAME_LOCATIONS.CORAL_MARK.LEFT]: [250, 450],
  [GAME_LOCATIONS.CORAL_MARK.MIDDLE]: [250, 800],
  [GAME_LOCATIONS.CORAL_MARK.RIGHT]: [250, 1175],

  [GAME_LOCATIONS.CORAL_STATION.LEFT]: [225, 125],
  [GAME_LOCATIONS.CORAL_STATION.RIGHT]: [225, 1475],

  [GAME_LOCATIONS.REEF.AB]: [665, 800],
  [GAME_LOCATIONS.REEF.CD]: [780, 1000],
  [GAME_LOCATIONS.REEF.EF]: [1020, 1000],
  [GAME_LOCATIONS.REEF.GH]: [1135, 800],
  [GAME_LOCATIONS.REEF.IJ]: [1020, 600],
  [GAME_LOCATIONS.REEF.KL]: [780, 600],

  [GAME_LOCATIONS.NET]: [1755, 375],
  [GAME_LOCATIONS.PROCESSOR]: [1200, 1500],

  [GAME_LOCATIONS.HANG.LEFT]: [1755, 1000],
  [GAME_LOCATIONS.HANG.MIDDLE]: [1755, 1225],
  [GAME_LOCATIONS.HANG.RIGHT]: [1755, 1450],

  [GAME_LOCATIONS.STARTING_LINE]: [1515, 655],
};
