export const LOCATIONS = {
  CORAL_MARK: {
    LEFT: "CORAL_MARK_LEFT",
    MIDDLE: "CORAL_MARK_MIDDLE",
    RIGHT: "CORAL_MARK_RIGHT",
  },
  CORAL_STATION: {
    LEFT: "CORAL_STATION_LEFT",
    RIGHT: "CORAL_STATION_RIGHT",
  },
  REEF: {
    AB: "REEF_AB",
    CD: "REEF_CD",
    EF: "REEF_EF",
    GH: "REEF_GH",
    IJ: "REEF_IJ",
    KL: "REEF_KL",
  },
  REEF_LEVEL: {
    1: "1",
    2: "2",
    3: "3",
    4: "4",
  },
  NET: "NET",
  PROCESSOR: "PROCESSOR",
  HANG: {
    LEFT: "HANG_LEFT",
    MIDDLE: "HANG_MIDDLE",
    RIGHT: "HANG_RIGHT",
  },
  HANG_LEVEL: {
    PARK: "PARK",
    DEEP: "DEEP",
    SHALLOW: "SHALLOW",
    FAIL: "FAIL",
  },
  STARTING_LINE: "STARTING_LINE",
};

// hard coded for the blue-zero, scoring table perspective
// encoding is: [x, y]
export const POSITIONS = {
  [LOCATIONS.CORAL_MARK.LEFT]: [290, 450],
  [LOCATIONS.CORAL_MARK.MIDDLE]: [290, 800],
  [LOCATIONS.CORAL_MARK.RIGHT]: [290, 1175],

  [LOCATIONS.CORAL_STATION.LEFT]: [225, 125],
  [LOCATIONS.CORAL_STATION.RIGHT]: [225, 1475],

  [LOCATIONS.REEF.AB]: [930, 600],
  [LOCATIONS.REEF.CD]: [1250, 600],
  [LOCATIONS.REEF.EF]: [1380, 790],
  [LOCATIONS.REEF.GH]: [1250, 1000],
  [LOCATIONS.REEF.IJ]: [930, 1000],
  [LOCATIONS.REEF.KL]: [830, 790],

  [LOCATIONS.NET]: [2150, 375],
  [LOCATIONS.PROCESSOR]: [1750, 1500],

  [LOCATIONS.HANG.LEFT]: [2150, 1000],
  [LOCATIONS.HANG.MIDDLE]: [2150, 1225],
  [LOCATIONS.HANG.RIGHT]: [2150, 1450],

  [LOCATIONS.STARTING_LINE]: [1750, 655],
};
